# Site settings
title: C++ Rocks!
email: hello <at> this domain
description: > # this means to ignore newlines until "baseurl:"
    This is a resource for developers writing modern C++, with a focus on the       latest revisions of the language: C++11 and C++14.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cpprocks.com" # the base hostname & protocol for your site
twitter_username: cpp_rocks

# Build settings
markdown: kramdown

# Output settings
permalink: /:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"